### ISSUE TITLE
Data inconsintency compared to current widget data

### ISSUE THREAD

**Issue by schliflo** [coverified/backend#12]
There's still something wrong here:
Looking at the [preview](https://deploy-preview-6--coverified-webcomponent.netlify.app/) of my [PR](https://github.com/coverified/webcomponent/pull/6) I noticed some inconsistencies compared to the current version:
| Current | Preview using the API | 
| -------- | --------------------- | 
| ![Screenshot 2020-04-21 at 00 04 55](https://user-images.githubusercontent.com/9881672/79804451-5f79af80-8364-11ea-84a1-3bbcfeebc32c.png) | ![Screenshot 2020-04-21 at 00 04 44](https://user-images.githubusercontent.com/9881672/79804479-6c969e80-8364-11ea-99d6-4b5edb3f752f.png) |

I checked the scheduled task, that triggers the feed ingestion over here: https://console.cloud.google.com/cloudscheduler?project=coverified2020 but it seems to be running fine.
@johanneshiry do you have an idea why this is happening?

**Comment by johanneshiry** [comment]
Are we using the same feed urls? In my first implementation I used the one from the google spreadsheet but didn't compared them with the github action here. Would you mind posting the feeds to be used here pls?!

**Comment by schliflo** [comment]
The currently used feeds are here: https://github.com/coverified/data/blob/master/.github/workflows/update.yml#L20
Seems like they pretty much match the feeds configured here: https://github.com/coverified/backend/blob/master/cfg/config.cfg
🤷‍♂️

**Comment by johanneshiry** [comment]
Thanks for the links - after thinking a little bit about it, it is obvious why there is a difference in the results. Everything is fine. It's not a bug, it's a feature.

--> as discussed initially, the backend filters the headlines for the following keywords: 

`keywords: ["corona", "covid", "sars-cov", "sars-cov", "sars-cov", "sars-cov", "epidemic"]`

(see https://github.com/coverified/backend/blob/master/cfg/config.cfg)

As you can see, the headlines on your left picture do not include one of the keywords, hence they are not persisted in the database. If you want to change this behavior pls let me know.

**Comment by schliflo** [comment]
Ah, this explains the differences. The current behaviour is, that it matches the keywords against headline & content and then includes the article in the result if any of the two match. 
In fact, currently each feed entry (JSON) gets flattened down to a single string and is then simply matched against the keyword list. Simple but effective :) (see https://github.com/coverified/webcomponent/blob/851a74b1392ceeca2bcee437edf99fbde426c8de/src/util.js#L46)
So this implementation only looks at the headlines and is therefore more restrictive. If we could extend the filter here to also include the content and maybe even the url, then we'll be on the same result level as the current implementation.
