### ISSUE TITLE
Bug: /latest only returns entries from single source

### ISSUE THREAD

**Issue by schliflo** [coverified/backend#7]
Example: https://api.coverified.info/api/v1/feed/latest/6 only returns `rki` entries at the moment.

Blocks https://github.com/coverified/webcomponent/pull/6

**Comment by johanneshiry** [comment]
~I'll check this tonight~
Just did a quick check and the reason for this behavior is, that the latest 6 feed entries are from the rki feed. If you increase the number to e.g. https://api.coverified.info/api/v1/feed/latest/20 you'll get other sources as well but they aren't as new as the rki sources are. 

I would conclude that this is not a bug, but the intended behavior for the "give me the latest n entries" api call.

**Comment by johanneshiry** [comment]
In addition to my last comment - maybe this is related to #5 and we should discuss a possible solution scenario/new feature for this need?
